-- tweaks/nvg_sticks_after_load conf
-- Restores NV across level changes / loads.

_G.dogma_tweaks_nvg_sticks_after_load_conf = {
	MOD_ID = "dogma/tweaks/nvg_sticks_after_load",
	DEFAULTS = {},
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "nvg_sticks_after_load_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_nvg_sticks_after_load_page_description",
		},
	})
end
