-- game/jump_pseudogiant_slam conf

_G.dogma_game_jump_pseudogiant_slam_conf = {
	MOD_ID = "dogma/game/jump_pseudogiant_slam",
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "game", "ui_mcm_menu_dogma_game", {
		id = "jump_pseudogiant_slam",
		sh = true,
		text = "ui_mcm_menu_dogma_game_jump_pseudogiant_slam",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_game_jump_pseudogiant_slam_page_description",
			},
		}),
	})
end
