-- hud/conditional_bhs conf
-- Show classic Body Health System HUD on damage, while a key is held, and/or with inventory open.

local defaults = {
	["sec"] = 30,
	["keybind"] = -1,
	["modifier"] = 0,
	["show_in_inventory"] = true,
}

_G.dogma_hud_conditional_bhs_conf = {
	MOD_ID = "dogma/hud/conditional_bhs",
	DEFAULTS = defaults,
	loaded = {
		sec = defaults["sec"],
		keybind = defaults["keybind"],
		modifier = defaults["modifier"],
		show_in_inventory = defaults["show_in_inventory"],
	},
}
