function on_mcm_load(options)
	local CONFIG = _G.dogma_hud_conditional_bhs_conf
	local kb_mod = (ui_mcm and ui_mcm.kb_mod_radio) or "radio_h"

	dogma_mcm.attach(options, "hud", "ui_mcm_menu_dogma_hud", {
		id = "conditional_bhs",
		sh = true,
		text = "ui_mcm_menu_dogma_hud_conditional_bhs",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_hud_conditional_bhs_page_description",
			},
			{
				id = "sec",
				type = "track",
				val = 2,
				min = 0,
				max = 60,
				step = 1,
				def = CONFIG.DEFAULTS["sec"],
				hint = "dogma_hud_conditional_bhs_sec",
			},
			{
				id = "keybind",
				type = "key_bind",
				val = 2,
				def = CONFIG.DEFAULTS["keybind"],
				hint = "dogma_hud_conditional_bhs_keybind",
			},
			{
				id = "modifier",
				type = kb_mod,
				val = 2,
				def = CONFIG.DEFAULTS["modifier"],
				hint = "mcm_kb_modifier",
				content = {
					{ 0, "mcm_kb_mod_none" },
					{ 1, "mcm_kb_mod_shift" },
					{ 2, "mcm_kb_mod_ctrl" },
					{ 3, "mcm_kb_mod_alt" },
				},
			},
			{
				id = "show_in_inventory",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["show_in_inventory"],
				hint = "dogma_hud_conditional_bhs_show_in_inventory",
			},
		}),
	})
end
