-- tweaks/escorts_have_no_friends conf (info-only MCM; always on while installed)

_G.dogma_tweaks_escorts_have_no_friends_conf = {
	MOD_ID = "dogma/tweaks/escorts_have_no_friends",
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "escorts_have_no_friends_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_escorts_have_no_friends_page_description",
		},
	})
end
