function on_mcm_load(options)
	dogma_mcm.attach(options, "npcs", "ui_mcm_menu_dogma_npcs", {
		id = "foliage",
		sh = true,
		text = "ui_mcm_menu_dogma_npcs_foliage",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_npcs_foliage_page_description",
			},
			{
				id = "push_to_cover",
				type = "check",
				text = "ui_mcm_dogma_npcs_foliage_push_to_cover",
				desc = "ui_mcm_dogma_npcs_foliage_push_to_cover_desc",
			},
		}),
	})
end
