-- tweaks/popup_messages conf

_G.dogma_tweaks_popup_messages_conf = {
	MOD_ID = "dogma/tweaks/popup_messages",
	DEFAULTS = {
		hide_quick_melee = true,
		offset_x = -35,
	},
	loaded = {},
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		id = "popup_messages",
		sh = true,
		text = "ui_mcm_menu_dogma_tweaks_popup_messages",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_tweaks_popup_messages_page_description",
			},
			{
				id = "hide_quick_melee",
				type = "check",
				val = 1,
				def = true,
				hint = "dogma_tweaks_popup_messages_hide_quick_melee",
			},
			{
				id = "offset_x",
				type = "track",
				val = 2,
				min = -512,
				max = 512,
				step = 1,
				def = -35,
				hint = "dogma_apm_offset_x",
			},
		}),
	})
end
