-- game/shared_stash conf

_G.dogma_game_shared_stash_conf = {
	MOD_ID = "dogma/game/shared_stash",
	DEFAULTS = {
		one_per_level = true,
	},
	loaded = {
		one_per_level = true,
	},
	-- Base inv_weight of workshop_item (Hideout Furniture)
	BASE_WEIGHT = 10,
	PDA_STASH_KEY = "dogma_game_shared_stash",
	WORKSHOP_SECTION = "placeable_workshop",
	WORKSHOP_ITEM = "workshop_item",
	SHARED_SECTION = "dogma_game_shared_stash",
}
