function on_mcm_load(options)
	local CONFIG = _G.dogma_player_campfire_conf
	dogma_mcm.attach(options, "player", "ui_mcm_menu_dogma_player", {
		id = "campfire",
		sh = true,
		text = "ui_mcm_menu_dogma_player_campfire",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_player_campfire_page_description",
			},
			{
				id = "body_sec",
				type = "track",
				val = 2,
				min = 5,
				max = 30,
				step = 1,
				def = CONFIG.DEFAULTS["body_sec"],
				hint = "dogma_player_campfire_body_sec",
			},
			{
				id = "limb_sec",
				type = "track",
				val = 2,
				min = 5,
				max = 30,
				step = 1,
				def = CONFIG.DEFAULTS["limb_sec"],
				hint = "dogma_player_campfire_limb_sec",
			},
		}),
	})
end
