function on_mcm_load(options)
	local CONF = _G.dogma_player_campfire_conf
	local D = CONF.defaults
	dogma_mcm.attach(options, "player", "ui_mcm_menu_dogma_player", {
		id = "campfire",
		sh = true,
		text = "ui_mcm_menu_dogma_player_campfire",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_player_campfire_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = D["enabled"],
				hint = "dogma_player_campfire_enabled",
			},
			{
				id = "interval",
				type = "track",
				val = 2,
				min = 1,
				max = 30,
				step = 0.5,
				def = D["interval"],
				hint = "dogma_player_campfire_interval",
			},
		}),
	})
end
