function on_mcm_load(options)
	local CONFIG = _G.dogma_player_campfire_conf
	dogma_mcm.attach(options, "player", "ui_mcm_menu_dogma_player", {
		id = "campfire",
		sh = true,
		text = "ui_mcm_menu_dogma_player_campfire",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_player_campfire_page_description",
			},
			{
				id = "temp_fill",
				type = "track",
				val = 2,
				min = 0,
				max = 75,
				step = 1,
				def = CONFIG.DEFAULTS["temp_fill"],
				hint = "dogma_player_campfire_temp_fill",
			},
			{
				id = "interval",
				type = "track",
				val = 2,
				min = 1,
				max = 30,
				step = 0.5,
				def = CONFIG.DEFAULTS["interval"],
				hint = "dogma_player_campfire_interval",
			},
		}),
	})
end
