-- fixes/fix_geiger_for_dynamic_rad_patches conf (LTX registers dynamic rad zones for dosimeter)

_G.dogma_fixes_fix_geiger_for_dynamic_rad_patches_conf = {
	MOD_ID = "dogma/fixes/fix_geiger_for_dynamic_rad_patches",
	DEFAULTS = {},
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "fixes", "ui_mcm_menu_dogma_fixes", {
		id = "fix_geiger_for_dynamic_rad_patches",
		sh = true,
		text = "ui_mcm_menu_dogma_fixes_fix_geiger_for_dynamic_rad_patches",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_fixes_fix_geiger_for_dynamic_rad_patches_page_description",
			},
		}),
	})
end
