-- Equipment Controls MCM

local CONFIG = _G.dogma_controls_equipment_controls_conf or {
	DEFAULTS = { ["auto_bolt_on_detector"] = true },
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "controls", "ui_mcm_menu_dogma_controls", {
		id = "equipment_controls",
		sh = true,
		text = "ui_mcm_menu_dogma_controls_equipment_controls",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_controls_equipment_controls_page_description",
			},
			{
				id = "auto_bolt_on_detector",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["auto_bolt_on_detector"],
				hint = "dogma_controls_equipment_controls_auto_bolt_on_detector",
			},
		}),
	})
end
