; D.O.G.M.A. feature manifest
; common is always included.
;
; 0 = off
; 1 = local build only (Ctrl+Shift+B / tools/build.sh)
; 2 = local + release (FOMOD / GitHub)

[features]
crafting/ammo=2
fx/radiation=2
fx/thirst=1
hud/fps=2
hud/nvg=1
hud/stalker_id=1
items/disassemble=1
items/drop=1
items/favourites=1
items/stripping=2
mcm/debug=1
mcm/search=2
misc/hard_defaults=1
misc/missions=1
misc/rf_receiver=1
mutants/audio=1
mutants/skinning=2
mutants/tweaks=2
npcs/companions=1
npcs/speed=2
pda/rep_warning=1
pda/stay_down=2
player/audio=1
player/campfire=1
player/pose_controls=2
player/real_prone=2
player/scanner_keys=1
tooltips/tweaks=2
tooltips/weapons=2
travel/fast_travel=0
travel/true_fast_travel=1
weapons/ammo_wheel=1
weapons/quick_fire=1
zoom/ads_zoom=2
zoom/free_zoom=2
