; D.O.G.M.A. feature manifest
; common is always included.
;
; 0 = off
; 1 = local build only (Ctrl+Shift+B / tools/build.sh)
; 2 = local + release (FOMOD / GitHub)

[features]
crafting/ammo=2
fx/radiation=2
fx/thirst=2
hud/fps=2
hud/nvg=2
items/disassemble=2
items/drop=2
items/favourites=2
items/stripping=2
mcm/debug=1
mcm/search=2
misc/missions=2
misc/remember_options=2
misc/rf_receiver=2
mutants/audio=1
mutants/skinning=2
mutants/tweaks=2
npcs/companions=2
npcs/speed=2
pda/rep_warning=2
pda/stay_down=2
player/audio=2
player/campfire=2
player/pose_controls=2
player/real_prone=2
player/scanner_keys=2
tooltips/loadout=2
tooltips/weapons=2
travel/fast_travel=0
travel/true_fast_travel=1
weapons/ammo_wheel=2
weapons/quick_fire=2
zoom/ads_zoom=2
zoom/free_zoom=2
