-- fixes/fix_footsteps_sfx conf (LTX/sounds always on while installed)

_G.dogma_fixes_fix_footsteps_sfx_conf = {
	MOD_ID = "dogma/fixes/fix_footsteps_sfx",
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "fixes", "ui_mcm_menu_dogma_fixes", {
		id = "fix_footsteps_sfx",
		sh = true,
		text = "ui_mcm_menu_dogma_fixes_fix_footsteps_sfx",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_fixes_fix_footsteps_sfx_page_description",
			},
		}),
	})
end
