-- fixes/fix_artifact_weights conf

_G.dogma_fixes_fix_artifact_weights_conf = {
	MOD_ID = "dogma/fixes/fix_artifact_weights",
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "fixes", "ui_mcm_menu_dogma_fixes", {
		id = "fix_artifact_weights",
		sh = true,
		text = "ui_mcm_menu_dogma_fixes_fix_artifact_weights",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_fixes_fix_artifact_weights_page_description",
			},
		}),
	})
end
