function on_mcm_load(options)
	local CONFIG = _G.dogma_npcs_companions_conf
	dogma_mcm.attach(options, "npcs", "ui_mcm_menu_dogma_npcs", {
		id = "companions",
		sh = true,
		text = "ui_mcm_menu_dogma_npcs_companions",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_npcs_companions_page_description",
			},
			{
				id = "teleport_key",
				type = "key_bind",
				val = 2,
				def = CONFIG.DEFAULTS["teleport_key"],
				hint = "dogma_npcs_companions_teleport_key",
			},
		}),
	})
end
