function on_mcm_load()
	local CONF = _G.dogma_prone_fix_conf
	local D = CONF.defaults
	return {
		id = "prone_fix",
		text = "ui_mcm_menu_dogma_prone_fix",
		gr = {
			{
				id = "main",
				sh = true,
				text = "Main",
				gr = dogma_mcm.with_header({
					{
						id = "hide_prone_bones",
						type = "check",
						val = 1,
						def = D["main/hide_prone_bones"],
						hint = "dogma_prone_fix_hide_prone_bones",
					},
					{
						id = "prone_damage_mult",
						type = "track",
						val = 2,
						min = 1,
						max = 2,
						step = 0.05,
						def = D["main/prone_damage_mult"],
						hint = "dogma_prone_fix_prone_damage_mult",
					},
				}),
			},
			{
				id = "development",
				sh = true,
				text = "Development",
				gr = dogma_mcm.with_header({
					{
						id = "heights_description",
						type = "desc",
						text = "Don't change camera heights unless you know what you're doing",
					},
					{
						id = "cam_height_stand",
						type = "track",
						val = 2,
						min = 0,
						max = 2,
						step = 0.01,
						def = D["development/cam_height_stand"],
						hint = "dogma_prone_fix_cam_height_stand",
					},
					{
						id = "cam_height_crouch",
						type = "track",
						val = 2,
						min = 0,
						max = 2,
						step = 0.01,
						def = D["development/cam_height_crouch"],
						hint = "dogma_prone_fix_cam_height_crouch",
					},
					{
						id = "cam_height_prone",
						type = "track",
						val = 2,
						min = 0,
						max = 2,
						step = 0.01,
						def = D["development/cam_height_prone"],
						hint = "dogma_prone_fix_cam_height_prone",
					},
					{ id = "line_debug", type = "line" },
					{
						id = "debug_overlay",
						type = "check",
						val = 1,
						def = D["development/debug_overlay"],
						hint = "dogma_prone_fix_debug_overlay",
					},
					{
						id = "debug_log",
						type = "check",
						val = 1,
						def = D["development/debug_log"],
						hint = "dogma_prone_fix_debug_log",
					},
				}),
			},
		},
	}, "dogma"
end
