function on_mcm_load(options)
	local CONF = _G.dogma_player_real_prone_conf
	local D = CONF.defaults
	dogma_mcm.attach(options, "player", "ui_mcm_menu_dogma_player", {
		id = "real_prone",
		sh = true,
		text = "ui_mcm_menu_dogma_player_real_prone",
		gr = dogma_mcm.with_header({
			{
				id = "hide_prone_bones",
				type = "check",
				val = 1,
				def = D["hide_prone_bones"],
				hint = "dogma_prone_fix_hide_prone_bones",
			},
			{
				id = "prone_damage_mult",
				type = "track",
				val = 2,
				min = 1,
				max = 2,
				step = 0.05,
				def = D["prone_damage_mult"],
				hint = "dogma_prone_fix_prone_damage_mult",
			},
			{ id = "line_camera", type = "line" },
			{
				id = "hdr_camera",
				type = "desc",
				text = "ui_mcm_dogma_prone_fix_hdr_camera",
			},
			{
				id = "heights_description",
				type = "desc",
				text = "ui_mcm_dogma_prone_fix_heights_description",
			},
			{
				id = "cam_height_stand",
				type = "track",
				val = 2,
				min = 0,
				max = 2,
				step = 0.01,
				def = D["cam_height_stand"],
				hint = "dogma_prone_fix_cam_height_stand",
			},
			{
				id = "cam_height_crouch",
				type = "track",
				val = 2,
				min = 0,
				max = 2,
				step = 0.01,
				def = D["cam_height_crouch"],
				hint = "dogma_prone_fix_cam_height_crouch",
			},
			{
				id = "cam_height_prone",
				type = "track",
				val = 2,
				min = 0,
				max = 2,
				step = 0.01,
				def = D["cam_height_prone"],
				hint = "dogma_prone_fix_cam_height_prone",
			},
		}),
	})
end
