function on_mcm_load(options)
	local CONF = _G.dogma_player_real_prone_conf
	local D = CONF.defaults
	dogma_mcm.attach(options, "player", "ui_mcm_menu_dogma_player", {
		id = "real_prone",
		sh = true,
		text = "ui_mcm_menu_dogma_player_real_prone",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_real_prone_page_description",
			},
			{
				id = "hide_prone_bones",
				type = "check",
				val = 1,
				def = D["hide_prone_bones"],
				hint = "dogma_prone_fix_hide_prone_bones",
			},
			{
				id = "prone_damage_mult",
				type = "track",
				val = 2,
				min = 1.1,
				max = 1.5,
				step = 0.05,
				def = D["prone_damage_mult"],
				hint = "dogma_prone_fix_prone_damage_mult",
			},
		}),
	})
end
