-- True Fast Travel: inject PDA path / destination map spots.
function on_xml_read()
	RegisterScriptCallback("on_xml_read", function(xml_file_name, xml_obj)
		if xml_file_name == [[ui\map_spots.xml]]
			or xml_file_name == [[ui\map_spots_16.xml]]
			or xml_file_name == [[ui\map_spots_21.xml]] then
			xml_obj:insertFromXMLString('#include "ui\\map_spots_dogma_true_fast_travel.xml"\n')
		end
	end)
end
