-- tweaks/box_loot_height conf
-- Raise items spawned from broken crates so they do not start in the floor.

_G.dogma_tweaks_box_loot_height_conf = {
	MOD_ID = "dogma/tweaks/box_loot_height",
	DEFAULTS = {
		height = 0.2,
	},
	loaded = {},
}

function on_mcm_load(options)
	local CONFIG = _G.dogma_tweaks_box_loot_height_conf
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "box_loot_height_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_box_loot_height_page_description",
		},
		{
			id = "box_loot_height",
			type = "track",
			val = 2,
			min = 0,
			max = 1,
			step = 0.05,
			def = CONFIG.DEFAULTS.height,
			hint = "dogma_tweaks_box_loot_height",
		},
	})
end
