function on_mcm_load(options)
	local CONFIG = _G.dogma_gameplay_campfire_healing_conf
	dogma_mcm.mcm.attach(options, "gameplay", "ui_mcm_menu_dogma_gameplay", {
		id = "campfire_healing",
		sh = true,
		text = "ui_mcm_menu_dogma_gameplay_campfire_healing",
		gr = dogma_mcm.mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_gameplay_campfire_healing_page_description",
			},
			{
				id = "body_sec",
				type = "track",
				val = 2,
				min = 30,
				max = 100,
				step = 1,
				def = CONFIG.DEFAULTS["body_sec"],
				hint = "dogma_gameplay_campfire_healing_body_sec",
			},
			{
				id = "limb_sec",
				type = "track",
				val = 2,
				min = 20,
				max = 100,
				step = 1,
				def = CONFIG.DEFAULTS["limb_sec"],
				hint = "dogma_gameplay_campfire_healing_limb_sec",
			},
		}),
	})
end
