-- items/workshop_shared_stash conf

local defaults = {}

_G.dogma_items_workshop_shared_stash_conf = {
	MOD_ID = "dogma/items/workshop_shared_stash",
	DEFAULTS = defaults,
	loaded = {},
	-- Base inv_weight of workshop_item (Hideout Furniture)
	BASE_WEIGHT = 10,
	PDA_STASH_KEY = "dogma_workshop_shared",
	WORKSHOP_SECTION = "placeable_workshop",
	WORKSHOP_ITEM = "workshop_item",
	SHARED_SECTION = "workshop_shared_stash",
}

function _G.dogma_items_workshop_shared_stash_conf:ensure_dogma()
	if not self.DOGMA then
		self.DOGMA = dogma_common.load(self.MOD_ID)
	end
	return self.DOGMA
end
