-- tweaks/highlight_name_in_pda_messages conf (info-only MCM; always on while installed)

_G.dogma_tweaks_highlight_name_in_pda_messages_conf = {
	MOD_ID = "dogma/tweaks/highlight_name_in_pda_messages",
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "highlight_name_in_pda_messages_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_highlight_name_in_pda_messages_page_description",
		},
	})
end
