function on_mcm_load(options)
	local CONFIG = _G.dogma_gameplay_stealth_conf
	dogma_mcm.attach(options, "gameplay", "ui_mcm_menu_dogma_gameplay", {
		id = "stealth",
		sh = true,
		text = "ui_mcm_menu_dogma_gameplay_stealth",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_gameplay_stealth_page_description",
			},
			{
				id = "scale",
				type = "track",
				val = 2,
				min = 0,
				max = 1,
				step = 0.05,
				def = CONFIG.DEFAULTS["scale"],
				hint = "dogma_gameplay_stealth_scale",
			},
			{
				id = "mult_stand",
				type = "track",
				val = 2,
				min = 0,
				max = 1,
				step = 0.05,
				def = CONFIG.DEFAULTS["mult_stand"],
				hint = "dogma_gameplay_stealth_mult_stand",
			},
			{
				id = "mult_crouch",
				type = "track",
				val = 2,
				min = 0,
				max = 1,
				step = 0.05,
				def = CONFIG.DEFAULTS["mult_crouch"],
				hint = "dogma_gameplay_stealth_mult_crouch",
			},
			{
				id = "mult_prone",
				type = "track",
				val = 2,
				min = 0,
				max = 1,
				step = 0.05,
				def = CONFIG.DEFAULTS["mult_prone"],
				hint = "dogma_gameplay_stealth_mult_prone",
			},
			{
				id = "icon",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["icon"],
				hint = "dogma_gameplay_stealth_icon",
			},
			{
				id = "debug",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["debug"],
				hint = "dogma_gameplay_stealth_debug",
			},
		}),
	})
end
