-- tweaks/no_waypoint_pda_msg conf (info-only MCM; always on while installed)

_G.dogma_tweaks_no_waypoint_pda_msg_conf = {
	MOD_ID = "dogma/tweaks/no_waypoint_pda_msg",
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "no_waypoint_pda_msg_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_no_waypoint_pda_msg_page_description",
		},
	})
end
