-- game/weapons_ban conf

local CONSTS = _G.dogma_game_weapons_ban_consts

_G.dogma_game_weapons_ban_conf = {
	MOD_ID = "dogma/game/weapons_ban",
	DEFAULTS = {
		extra_start_ammo_boxes = CONSTS.EXTRA_START_AMMO_BOXES,
		start_weapons_59_parts = CONSTS.START_WEAPONS_59_PARTS,
	},
	loaded = {},
}

function _G.dogma_game_weapons_ban_conf:ensure_dogma()
	dogma.load(self.MOD_ID)
	return dogma
end

function on_mcm_load(options)
	local CONFIG = _G.dogma_game_weapons_ban_conf
	local D = CONFIG.DEFAULTS

	dogma_mcm.attach(options, "game", "ui_mcm_menu_dogma_game", {
		id = "weapons_ban",
		sh = true,
		text = "ui_mcm_menu_dogma_game_weapons_ban",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_game_weapons_ban_page_description",
			},
			{
				id = "extra_start_ammo_boxes",
				type = "track",
				val = 2,
				min = 0,
				max = 5,
				step = 1,
				def = D.extra_start_ammo_boxes,
				hint = "dogma_game_weapons_ban_extra_start_ammo_boxes",
			},
			{
				id = "start_weapons_59_parts",
				type = "check",
				val = 1,
				def = D.start_weapons_59_parts,
				hint = "dogma_game_weapons_ban_start_weapons_59_parts",
			},
		}),
	})
end
