function on_mcm_load(options)
	local CONFIG = _G.dogma_items_favourites_conf
	dogma_mcm.attach(options, "items", "ui_mcm_menu_dogma_items", {
		id = "favourites",
		sh = true,
		text = "ui_mcm_menu_dogma_items_favourites",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_items_favourites_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["enabled"],
				hint = "dogma_items_favourites_enabled",
			},
		}),
	})
end
