-- tweaks/no_afterglow_delay conf

_G.dogma_tweaks_no_afterglow_delay_conf = {
	MOD_ID = "dogma/tweaks/no_afterglow_delay",
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		id = "no_afterglow_delay",
		sh = true,
		text = "ui_mcm_menu_dogma_tweaks_no_afterglow_delay",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_tweaks_no_afterglow_delay_page_description",
			},
		}),
	})
end
