-- tweaks/dodge_pseudogiant_slam_if_airborne conf (info-only MCM; always on while installed)

_G.dogma_tweaks_dodge_pseudogiant_slam_if_airborne_conf = {
	MOD_ID = "dogma/tweaks/dodge_pseudogiant_slam_if_airborne",
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "dodge_pseudogiant_slam_if_airborne_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_dodge_pseudogiant_slam_if_airborne_page_description",
		},
	})
end
