function on_mcm_load(options)
	local CONFIG = _G.dogma_player_audio_conf
	dogma_mcm.attach(options, "player", "ui_mcm_menu_dogma_player", {
		id = "audio",
		sh = true,
		text = "ui_mcm_menu_dogma_player_audio",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_player_audio_page_description",
			},
			{
				id = "mute_player_voice",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["mute_player_voice"],
				hint = "dogma_player_audio_mute_player_voice",
			},
		}),
	})
end
