-- gui/hide_torn_off_patches conf

_G.dogma_gui_hide_torn_off_patches_conf = {
	MOD_ID = "dogma/gui/hide_torn_off_patches",
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "gui", "ui_mcm_menu_dogma_gui", {
		id = "hide_torn_off_patches",
		sh = true,
		text = "ui_mcm_menu_dogma_gui_hide_torn_off_patches",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_gui_hide_torn_off_patches_page_description",
			},
		}),
	})
end
