-- tweaks/nvg_can_set_default_gain conf
-- Beef default gain step lives on Beef's MCM (override injects the slider).

_G.dogma_tweaks_nvg_can_set_default_gain_conf = {
	MOD_ID = "dogma/tweaks/nvg_can_set_default_gain",
	DEFAULTS = {
		["default_gain_step"] = 1,
	},
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "nvg_can_set_default_gain_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_nvg_can_set_default_gain_page_description",
		},
	})
end
