-- extensions/atmospherics conf

_G.dogma_extensions_atmospherics_conf = {
	MOD_ID = "dogma/extensions/atmospherics",
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "extensions", "ui_mcm_menu_dogma_extensions", {
		id = "atmospherics",
		sh = true,
		text = "ui_mcm_menu_dogma_extensions_atmospherics",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_extensions_atmospherics_page_description",
			},
		}),
	})
end
