-- extensions/safe_atmos_visibility conf

_G.dogma_extensions_safe_atmos_visibility_conf = {
	MOD_ID = "dogma/extensions/safe_atmos_visibility",
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "extensions", "ui_mcm_menu_dogma_extensions", {
		id = "safe_atmos_visibility",
		sh = true,
		text = "ui_mcm_menu_dogma_extensions_safe_atmos_visibility",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_extensions_safe_atmos_visibility_page_description",
			},
		}),
	})
end
