-- tweaks/quieter_bush_rustle_sfx_for_dark_signal conf (info-only MCM; quieter bush collide SFX always on while installed)



_G.dogma_tweaks_quieter_bush_rustle_sfx_for_dark_signal_conf = {

	MOD_ID = "dogma/tweaks/quieter_bush_rustle_sfx_for_dark_signal",

}


function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "quieter_bush_rustle_sfx_for_dark_signal_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_quieter_bush_rustle_sfx_for_dark_signal_page_description",
		},
	})
end
