-- hud/stalker_id conf

local defaults = {
	["dead_id"] = true,
	["name_id"] = true,
	["time_id"] = true,
	["rank_id"] = true,
	["speed_id"] = 0.2,
	["targ_l"] = 0.984,
	["name_y"] = 16,
	["rank_y"] = 34,
	["icon_y"] = 56,
	["colors/name_r"] = 200,
	["colors/name_g"] = 200,
	["colors/name_b"] = 200,
	["colors/rank_r"] = 150,
	["colors/rank_g"] = 150,
	["colors/rank_b"] = 150,
}

_G.dogma_hud_stalker_id_conf = {
	MOD_ID = "dogma/hud/stalker_id",
	DEFAULTS = defaults,
	loaded = {
		dead_id = defaults["dead_id"],
		name_id = defaults["name_id"],
		time_id = defaults["time_id"],
		rank_id = defaults["rank_id"],
		speed_id = defaults["speed_id"],
		targ_l = defaults["targ_l"],
		name_y = defaults["name_y"],
		rank_y = defaults["rank_y"],
		icon_y = defaults["icon_y"],
		name_r = defaults["colors/name_r"],
		name_g = defaults["colors/name_g"],
		name_b = defaults["colors/name_b"],
		rank_r = defaults["colors/rank_r"],
		rank_g = defaults["colors/rank_g"],
		rank_b = defaults["colors/rank_b"],
	},
}
