-- hud/stalker_id conf

local defaults = {
	["dead_id"] = true,
	["name_id"] = true,
	["rank_id"] = true,
	["name_y"] = 20,
	["rank_y"] = 32,
	["icon_y"] = 60,
	["name_a"] = 100,
	["rank_a"] = 100,
	["icon_a"] = 100,
}

_G.dogma_hud_stalker_id_conf = {
	MOD_ID = "dogma/hud/stalker_id",
	DEFAULTS = defaults,
	loaded = {
		dead_id = defaults["dead_id"],
		name_id = defaults["name_id"],
		rank_id = defaults["rank_id"],
		name_y = defaults["name_y"],
		rank_y = defaults["rank_y"],
		icon_y = defaults["icon_y"],
		name_a = defaults["name_a"],
		rank_a = defaults["rank_a"],
		icon_a = defaults["icon_a"],
	},
}
