function on_mcm_load(options)
	local CONFIG = _G.dogma_gui_nearby_pickup_labels_conf
	dogma_mcm.attach(options, "gui", "ui_mcm_menu_dogma_gui", {
		id = "nearby_pickup_labels",
		sh = true,
		text = "ui_mcm_menu_dogma_gui_nearby_pickup_labels",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_gui_nearby_pickup_labels_page_description",
			},
			{
				id = "range",
				type = "track",
				val = 2,
				min = 0,
				max = 10,
				step = 0.05,
				def = CONFIG.DEFAULTS["range"],
				hint = "dogma_gui_nearby_pickup_labels_range",
			},
		}),
	})
end
