-- tweaks/qaw_reordering conf

_G.dogma_tweaks_qaw_reordering_conf = {
	MOD_ID = "dogma/tweaks/qaw_reordering",
	DEFAULTS = {
		enabled = true,
		reorder_key = -1,
		persist_slots = false,
	},
	loaded = {
		enabled = true,
		reorder_key = 0,
		persist_slots = false,
	},
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		id = "qaw_reordering",
		sh = true,
		text = "ui_mcm_menu_dogma_tweaks_qaw_reordering",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_tweaks_qaw_reordering_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = true,
				hint = "dogma_tweaks_qaw_reordering_enabled",
			},
			{
				id = "reorder_key",
				type = "key_bind",
				val = 2,
				def = -1,
				hint = "dogma_qaw_reordering_key",
			},
			{
				id = "persist_slots",
				type = "check",
				val = 1,
				def = false,
				hint = "dogma_qaw_persist_slots",
			},
		}),
	})
end
