function on_mcm_load(options)
	local CONFIG = _G.dogma_items_stripping_conf
	local function kb_bind(id, hint)
		return {
			id = id,
			type = "key_bind",
			val = 2,
			def = CONFIG.DEFAULTS[id],
			hint = hint,
		}
	end

	local function kb_modifier(id)
		local kb_mod = (ui_mcm and ui_mcm.kb_mod_radio) or "radio_h"
		return {
			id = id,
			type = kb_mod,
			val = 2,
			def = CONFIG.DEFAULTS[id],
			hint = "mcm_kb_modifier",
			content = {
				{ 0, "mcm_kb_mod_none" },
				{ 1, "mcm_kb_mod_shift" },
				{ 2, "mcm_kb_mod_ctrl" },
				{ 3, "mcm_kb_mod_alt" },
			},
		}
	end

	local function kb_mode(id)
		local kb_mod = (ui_mcm and ui_mcm.kb_mod_radio) or "radio_h"
		return {
			id = id,
			type = kb_mod,
			val = 2,
			def = CONFIG.DEFAULTS[id],
			hint = "mcm_kb_mode",
			content = {
				{ 0, "mcm_kb_mode_press" },
				{ 2, "mcm_kb_mode_hold" },
			},
		}
	end

	dogma_mcm.attach(options, "items", "ui_mcm_menu_dogma_items", {
		id = "stripping",
		sh = true,
		text = "ui_mcm_menu_dogma_items_stripping",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_stripping_page_description",
			},
			{
				id = "intercept_disassemble",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["intercept_disassemble"],
				hint = "dogma_stripping_intercept_disassemble",
			},
			kb_bind("key", "dogma_stripping_key"),
			kb_modifier("key_modifier"),
			kb_mode("key_mode"),
			{
				id = "keep_parts_with_weapon",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["keep_parts_with_weapon"],
				hint = "dogma_stripping_keep_parts_with_weapon",
			},
			{
				id = "block_companion_special_items",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["block_companion_special_items"],
				hint = "dogma_stripping_block_companion_special_items",
			},
		}),
	})
end
