-- tweaks/hide_geiger_screen_text conf

_G.dogma_tweaks_hide_geiger_screen_text_conf = {
	MOD_ID = "dogma/tweaks/hide_geiger_screen_text",
	DEFAULTS = { enabled = true },
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		id = "hide_geiger_screen_text",
		sh = true,
		text = "ui_mcm_menu_dogma_tweaks_hide_geiger_screen_text",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_tweaks_hide_geiger_screen_text_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = true,
				hint = "dogma_tweaks_hide_geiger_screen_text_enabled",
			},
		}),
	})
end
