-- game/nvg_tweaks conf

_G.dogma_game_nvg_tweaks_conf = {
	MOD_ID = "dogma/game/nvg_tweaks",
	DEFAULTS = {
		sticks_after_load = true,
		default_gain_step = 1,
	},
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "game", "ui_mcm_menu_dogma_game", {
		id = "nvg_tweaks",
		sh = true,
		text = "ui_mcm_menu_dogma_game_nvg_tweaks",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_game_nvg_tweaks_page_description",
			},
			{
				id = "sticks_after_load",
				type = "check",
				val = 1,
				def = true,
				hint = "dogma_game_nvg_tweaks_sticks_after_load",
			},
			{
				id = "default_gain_step",
				type = "track",
				val = 2,
				min = 0,
				max = 3,
				step = 1,
				def = 1,
				hint = "dogma_game_nvg_tweaks_default_gain_step",
			},
		}),
	})
end
