-- extensions/dao_less_gc conf

_G.dogma_extensions_dao_less_gc_conf = {
	MOD_ID = "dogma/extensions/dao_less_gc",
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "extensions", "ui_mcm_menu_dogma_extensions", {
		id = "dao_less_gc",
		sh = true,
		text = "ui_mcm_menu_dogma_extensions_dao_less_gc",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_extensions_dao_less_gc_page_description",
			},
		}),
	})
end
