-- Safe Spawn countdown HUD static. AddCustomStatic native-crashes if this node is missing.
local on_xml_read_anon_1 = function(xml_file_name, xml_obj)
	if xml_file_name ~= [[ui\ui_custom_msgs.xml]] then
		return
	end
	xml_obj:insertFromXMLString([[	<dogma_game_safe_spawn_prompt x="0" y="651" width="1024" height="56" complex_mode="1">
	<text font="graffiti22" r="200" g="200" b="200" a="255" align="c" vert_align="t"/>
	</dogma_game_safe_spawn_prompt>]])
	_G.dogma_game_safe_spawn_xml = true
end

function on_xml_read()
	RegisterScriptCallback("on_xml_read", on_xml_read_anon_1)
end
