-- tweaks/melancholy_night_ambient_x2 conf (info-only MCM; always on while installed)

_G.dogma_tweaks_melancholy_night_ambient_x2_conf = {
	MOD_ID = "dogma/tweaks/melancholy_night_ambient_x2",
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "melancholy_night_ambient_x2_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_melancholy_night_ambient_x2_page_description",
		},
	})
end
