function on_mcm_load(options)
	local CONFIG = _G.dogma_gameplay_melee_skinning_conf
	dogma_mcm.attach(options, "gameplay", "ui_mcm_menu_dogma_gameplay", {
		id = "melee_skinning",
		sh = true,
		text = "ui_mcm_menu_dogma_gameplay_melee_skinning",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_gameplay_melee_skinning_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["enabled"],
				hint = "dogma_gameplay_melee_skinning_enabled",
			},
			{
				id = "pickup_delay_ms",
				type = "track",
				val = 2,
				min = 0,
				max = 1000,
				step = 25,
				def = CONFIG.DEFAULTS["pickup_delay_ms"],
				hint = "dogma_gameplay_melee_skinning_pickup_delay_ms",
			},
		}),
	})
end
