-- tweaks/fix_task_done_msg_crash conf (info-only MCM; always on while installed)

_G.dogma_tweaks_fix_task_done_msg_crash_conf = {
	MOD_ID = "dogma/tweaks/fix_task_done_msg_crash",
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "fix_task_done_msg_crash_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_fix_task_done_msg_crash_page_description",
		},
	})
end
