-- controls/true_prone conf

local defaults = {
	["hide_prone_bones"] = true,
	["prone_damage_mult"] = 1.1,
}

_G.dogma_controls_true_prone_conf = {
	MOD_ID = "dogma/controls/true_prone",
	DEFAULTS = defaults,
	loaded = {
		enabled = true,
		debug_log = true,
		debug_overlay = false,
		hide_prone_bones = defaults["hide_prone_bones"],
		cam_height_stand = 1.65,
		cam_height_crouch = 1.2,
		cam_height_prone = 0.45,
		prone_damage_mult = defaults["prone_damage_mult"],
	},
}
