function on_mcm_load(options)
	local CONFIG = _G.dogma_gameplay_death_spectator_conf
	dogma.mcm.attach(options, "gameplay", "ui_mcm_menu_dogma_gameplay", {
		id = "death_spectator",
		sh = true,
		text = "ui_mcm_menu_dogma_gameplay_death_spectator",
		gr = dogma.mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_gameplay_death_spectator_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["enabled"],
				hint = "dogma_gameplay_death_spectator_enabled",
			},
		}),
	})
end
