-- game/true_fast_travel conf

_G.dogma_game_true_fast_travel_conf = {
	MOD_ID = "dogma/game/true_fast_travel",
	DEFAULTS = {
		["block_transition_in_combat"] = true,
		["block_travel_when_unfit"] = true,
		["screen_msg_duration"] = 4,
		["time_factor_travel"] = 1.0,
		["time_factor_backslide"] = 0.05,
		["cam_speed_mult"] = 1.0,
		["backslide_clear_m"] = 25,
		["pause_on_stop"] = true,
		["pause_on_done"] = true,
		["show_hud_during_travel"] = false,
		["path_preview"] = true,
		["visited_radius_m"] = 30,
		["companion_teleport_key"] = -1,
	},
}
