-- extensions/dynamic_anomalies_overhaul conf

_G.dogma_extensions_dynamic_anomalies_overhaul_conf = {
	MOD_ID = "dogma/extensions/dynamic_anomalies_overhaul",
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "extensions", "ui_mcm_menu_dogma_extensions", {
		id = "dynamic_anomalies_overhaul",
		sh = true,
		text = "ui_mcm_menu_dogma_extensions_dynamic_anomalies_overhaul",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_extensions_dynamic_anomalies_overhaul_page_description",
			},
		}),
	})
end
