-- hud/fps_counter conf

_G.dogma_hud_fps_counter_conf = {
	MOD_ID = "dogma/hud/fps_counter",
	defaults = {
		["colors/graph_border_a"] = 200,
		["colors/graph_border_b"] = 150,
		["colors/graph_border_g"] = 150,
		["colors/graph_border_r"] = 150,
		["colors/graph_line_a"] = 150,
		["colors/graph_line_b"] = 0,
		["colors/graph_line_g"] = 255,
		["colors/graph_line_r"] = 255,
		["colors/text_a"] = 200,
		["colors/text_b"] = 255,
		["colors/text_g"] = 255,
		["colors/text_r"] = 255,
		["display"] = 0,
		["enabled_default"] = true,
		["max_fps"] = 144,
		["minmax_window"] = 5,
		["pos_anchor"] = 0,
		["pos_x"] = 0,
		["pos_y"] = 0,
		["refresh_rate"] = 3,
		["sample_window"] = 0.5,
		["toggle_key"] = -1,
	},
}
