-- tweaks/no_item_popup_knife_quick_melee conf (info-only MCM; always on while installed)

_G.dogma_tweaks_no_item_popup_knife_quick_melee_conf = {
	MOD_ID = "dogma/tweaks/no_item_popup_knife_quick_melee",
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "no_item_popup_knife_quick_melee_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_no_item_popup_knife_quick_melee_page_description",
		},
	})
end
