-- fixes/fix_damage_limb_allocation conf

_G.dogma_fixes_fix_damage_limb_allocation_conf = {
	MOD_ID = "dogma/fixes/fix_damage_limb_allocation",
	DEFAULTS = { enabled = true },
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "fixes", "ui_mcm_menu_dogma_fixes", {
		id = "fix_damage_limb_allocation",
		sh = true,
		text = "ui_mcm_menu_dogma_fixes_fix_damage_limb_allocation",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_fixes_fix_damage_limb_allocation_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = true,
				hint = "dogma_fixes_fix_damage_limb_allocation_enabled",
			},
		}),
	})
end
