function on_mcm_load(options)
	local CONF = _G.dogma_weapons_ammo_wheel_conf
	local D = CONF.defaults
	dogma_mcm.attach(options, "weapons", "ui_mcm_menu_dogma_weapons", {
		id = "ammo_wheel",
		sh = true,
		text = "ui_mcm_menu_dogma_weapons_ammo_wheel",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_ammo_wheel_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = D["enabled"],
				hint = "dogma_ammo_wheel_enabled",
			},
		}),
	})
end
