-- tweaks/fanatic_stays_in_cordon conf (info-only MCM; always on while installed)

_G.dogma_tweaks_fanatic_stays_in_cordon_conf = {
	MOD_ID = "dogma/tweaks/fanatic_stays_in_cordon",
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "fanatic_stays_in_cordon_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_fanatic_stays_in_cordon_page_description",
		},
	})
end
