function on_mcm_load(options)
	local CONFIG = _G.dogma_travel_fast_travel_conf
	dogma_mcm.attach(options, "travel", "ui_mcm_menu_dogma_travel", {
		id = "fast_travel",
		sh = true,
		text = "ui_mcm_menu_dogma_travel_fast_travel",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_fast_travel_page_description",
			},
			{
				id = "message_duration",
				type = "track",
				val = 2,
				min = 3,
				max = 60,
				step = 1,
				def = CONFIG.DEFAULTS["message_duration"],
				hint = "dogma_fast_travel_message_duration",
			},
			{
				id = "block_transition_in_combat",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["block_transition_in_combat"],
				hint = "dogma_fast_travel_block_transition_in_combat",
			},
			{
				id = "show_ambush_range",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["show_ambush_range"],
				hint = "dogma_fast_travel_show_ambush_range",
			},
		}),
	})
end
