-- tweaks/fix_ammo_wheel_hotkeys conf (info-only MCM; always on while installed)

_G.dogma_tweaks_fix_ammo_wheel_hotkeys_conf = {
	MOD_ID = "dogma/tweaks/fix_ammo_wheel_hotkeys",
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "fix_ammo_wheel_hotkeys_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_fix_ammo_wheel_hotkeys_page_description",
		},
	})
end
