-- input/dialogue conf

_G.dogma_input_dialogue_conf = {
	MOD_ID = "dogma/input/dialogue",
	DEFAULTS = {
		-- DIK_TAB
		["close_key"] = 15,
	},
	loaded = {},
}

function on_mcm_load(options)
	local CONFIG = _G.dogma_input_dialogue_conf
	dogma_mcm.attach(options, "input", "ui_mcm_menu_dogma_input", {
		id = "dialogue",
		sh = true,
		text = "ui_mcm_menu_dogma_input_dialogue",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_input_dialogue_page_description",
			},
			{
				id = "close_key",
				type = "key_bind",
				val = 2,
				def = CONFIG.DEFAULTS["close_key"],
				hint = "dogma_input_dialogue_close_key",
			},
		}),
	})
end
