-- game/passive_detector_beeps conf

_G.dogma_game_passive_detector_beeps_conf = {
	MOD_ID = "dogma/game/passive_detector_beeps",
	DEFAULTS = {
		beep_holstered = true,
		hide_icon = true,
	},
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "game", "ui_mcm_menu_dogma_game", {
		id = "passive_detector_beeps",
		sh = true,
		text = "ui_mcm_menu_dogma_game_passive_detector_beeps",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_game_passive_detector_beeps_page_description",
			},
			{
				id = "beep_holstered",
				type = "check",
				val = 1,
				def = true,
				hint = "dogma_game_passive_detector_beeps_beep_holstered",
			},
			{
				id = "hide_icon",
				type = "check",
				val = 1,
				def = true,
				hint = "dogma_game_passive_detector_beeps_hide_icon",
			},
		}),
	})
end
