function on_mcm_load(options)
	local CONFIG = _G.dogma_fx_health_conf
	dogma_mcm.attach(options, "fx", "ui_mcm_menu_dogma_fx", {
		id = "health",
		sh = true,
		text = "ui_mcm_menu_dogma_fx_health",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_fx_health_page_description",
			},
			{
				id = "enable",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["enable"],
				hint = "dogma_fx_health_enable",
			},
			{
				id = "hp_start",
				type = "track",
				val = 2,
				min = 0.5,
				max = 1,
				step = 0.05,
				def = CONFIG.DEFAULTS["hp_start"],
				hint = "dogma_fx_health_hp_start",
			},
			{
				id = "hp_end",
				type = "track",
				val = 2,
				min = 0,
				max = 0.5,
				step = 0.05,
				def = CONFIG.DEFAULTS["hp_end"],
				hint = "dogma_fx_health_hp_end",
			},
			{
				id = "intensity",
				type = "track",
				val = 2,
				min = 0,
				max = 1,
				step = 0.05,
				def = CONFIG.DEFAULTS["intensity"],
				hint = "dogma_fx_health_intensity",
			},
		}),
	})
end
