-- game/global_stash conf

_G.dogma_game_global_stash_conf = {
	MOD_ID = "dogma/game/global_stash",
	DEFAULTS = {
		pickup_key = -1,
	},
	loaded = {},
}

function on_mcm_load(options)
	local CONFIG = _G.dogma_game_global_stash_conf
	dogma_mcm.attach(options, "game", "ui_mcm_menu_dogma_game", {
		id = "global_stash",
		sh = true,
		text = "ui_mcm_menu_dogma_game_global_stash",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_game_global_stash_page_description",
			},
			{
				id = "pickup_key",
				type = "key_bind",
				val = 2,
				def = CONFIG.DEFAULTS.pickup_key,
				hint = "dogma_game_global_stash_pickup_key",
			},
		}),
	})
end
