-- items/belt_glowsticks conf

local defaults = {
	["light_range"] = 1.0,
	["brightness"] = 1.0,
	["luminosity"] = 1.0,
	["disable_messages"] = false,
}

_G.dogma_items_belt_glowsticks_conf = {
	MOD_ID = "dogma/items/belt_glowsticks",
	DEFAULTS = defaults,
	loaded = {
		light_range = defaults["light_range"],
		brightness = defaults["brightness"],
		luminosity = defaults["luminosity"],
		disable_messages = defaults["disable_messages"],
	},
}
