function on_mcm_load(options)
	local CONFIG = _G.dogma_items_belt_glowsticks_conf
	dogma_mcm.attach(options, "items", "ui_mcm_menu_dogma_items", {
		id = "belt_glowsticks",
		sh = true,
		text = "ui_mcm_menu_dogma_items_belt_glowsticks",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_items_belt_glowsticks_page_description",
			},
			{
				id = "light_range",
				type = "track",
				val = 2,
				def = CONFIG.DEFAULTS["light_range"],
				min = 1.0,
				max = 2.0,
				step = 0.05,
				hint = "dogma_items_belt_glowsticks_light_range",
			},
			{
				id = "brightness",
				type = "track",
				val = 2,
				def = CONFIG.DEFAULTS["brightness"],
				min = 0.0,
				max = 1.0,
				step = 0.05,
				hint = "dogma_items_belt_glowsticks_brightness",
			},
			{
				id = "luminosity",
				type = "track",
				val = 2,
				def = CONFIG.DEFAULTS["luminosity"],
				min = 0.0,
				max = 1.0,
				step = 0.05,
				hint = "dogma_items_belt_glowsticks_luminosity",
			},
			{
				id = "disable_messages",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["disable_messages"],
				hint = "dogma_items_belt_glowsticks_disable_messages",
			},
		}),
	})
end
