-- gui/invictus_checker conf

_G.dogma_gui_invictus_checker_conf = {
	MOD_ID = "dogma/gui/invictus_checker",
	DEFAULTS = {
		enabled = true,
	},
	loaded = {},
}

function on_mcm_load(options)
	local CONFIG = _G.dogma_gui_invictus_checker_conf
	dogma_mcm.attach(options, "gui", "ui_mcm_menu_dogma_gui", {
		id = "invictus_checker",
		sh = true,
		text = "ui_mcm_menu_dogma_gui_invictus_checker",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_gui_invictus_checker_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS.enabled,
				hint = "dogma_gui_invictus_checker_enabled",
			},
		}),
	})
end
