-- Invictus Checker: HUD static for the Clamitas alert.
function on_xml_read()
	RegisterScriptCallback("on_xml_read", function(xml_file_name, xml_obj)
		if xml_file_name ~= [[ui\ui_custom_msgs.xml]] then
			return
		end
		xml_obj:insertFromXMLString([[	<dogma_invictus_clamitas x="0" y="36" width="1024" height="56">
		<text font="graffiti32" r="220" g="32" b="32" a="255" align="c" vert_align="c"/>
	</dogma_invictus_clamitas>]])
	end)
end
