function on_mcm_load(options)
	local CONFIG = _G.dogma_fx_bleed_conf
	dogma_mcm.attach(options, "fx", "ui_mcm_menu_dogma_fx", {
		id = "bleed",
		sh = true,
		text = "ui_mcm_menu_dogma_fx_bleed",
		gr = dogma_mcm.with_header({
			{
				id = "style_preview",
				type = "slide",
				link = CONFIG.MCM_STYLE_PREVIEW,
				text = "ui_mcm_dogma_fx_bleed_style_preview",
				size = CONFIG.MCM_STYLE_PREVIEW_SIZE,
				stretch = true,
				spacing = 12,
			},
			{
				id = "enable",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["enable"],
				hint = "dogma_fx_bleed_enable",
			},
			{
				id = "style",
				type = "list",
				val = 2,
				def = CONFIG.DEFAULTS["style"],
				hint = "dogma_fx_bleed_style",
				content = {
					{ 0, "style_0" },
					{ 1, "style_1" },
					{ 2, "style_2" },
				},
			},
			{
				id = "scale",
				type = "list",
				val = 2,
				def = CONFIG.DEFAULTS["scale"],
				hint = "dogma_fx_bleed_scale",
				content = {
					{ 0, "scale_25" },
					{ 1, "scale_50" },
					{ 2, "scale_100" },
				},
			},
			{
				id = "max_alpha",
				type = "track",
				val = 2,
				min = 0,
				max = 1,
				step = 0.05,
				def = CONFIG.DEFAULTS["max_alpha"],
				hint = "dogma_fx_bleed_max_alpha",
			},
		}),
	})
end
