--[[
    Vendored xlibs (Damian Sirbu). Use via dogma.xlibs.xobject, not xobject.
]]

local M = getfenv(1)

M["xconst"] = __dogma_xconst
M["xstring"] = __dogma_xstring
M["xtable"] = __dogma_xtable
M["xmath"] = __dogma_xmath
M["xfs"] = __dogma_xfs
M["xltx"] = __dogma_xltx
M["xtime"] = __dogma_xtime
M["xslice"] = __dogma_xslice
M["xtrace"] = __dogma_xtrace
M["xttltable"] = __dogma_xttltable
M["xlog"] = __dogma_xlog
M["xevent"] = __dogma_xevent
M["xbus"] = __dogma_xbus
M["xpp"] = __dogma_xpp
M["xprofiler"] = __dogma_xprofiler
M["xinspect"] = __dogma_xinspect
M["xprops"] = __dogma_xprops
M["xchange"] = __dogma_xchange
M["xmcm"] = __dogma_xmcm
M["xobject"] = __dogma_xobject
M["xlevel"] = __dogma_xlevel
M["xinventory"] = __dogma_xinventory
M["xcreature"] = __dogma_xcreature
M["xactor"] = __dogma_xactor
M["xdata"] = __dogma_xdata
M["xsquad"] = __dogma_xsquad
M["xsmart"] = __dogma_xsmart
M["xsmart_spawn"] = __dogma_xsmart_spawn
M["xstash"] = __dogma_xstash
M["xpda"] = __dogma_xpda
M["xsound"] = __dogma_xsound
M["xcombat"] = __dogma_xcombat
