function on_mcm_load(options)
	local CONF = _G.dogma_pda_qol_conf
	local D = CONF.defaults
	dogma_mcm.attach(options, "pda", "ui_mcm_menu_dogma_pda", {
		id = "qol",
		sh = true,
		text = "ui_mcm_menu_dogma_pda_qol",
		gr = dogma_mcm.with_header({
			{
				id = "main_description",
				type = "desc",
				text = "ui_mcm_dogma_dont_reequip_pda_main_description",
			},
			{
				id = "after_inventory",
				type = "check",
				val = 1,
				def = D["after_inventory"],
				hint = "dogma_dont_reequip_pda_after_inventory",
			},
			{
				id = "after_loot",
				type = "check",
				val = 1,
				def = D["after_loot"],
				hint = "dogma_dont_reequip_pda_after_loot",
			},
			{
				id = "after_teleport",
				type = "check",
				val = 1,
				def = D["after_teleport"],
				hint = "dogma_dont_reequip_pda_after_teleport",
			},
		}),
	})
end
