function on_mcm_load()
	local CONF = _G.dogma_dont_reequip_pda_conf
	local D = CONF.defaults
	return {
		id = "dont_reequip_pda",
		text = "ui_mcm_menu_dogma_dont_reequip_pda",
		gr = {
			{
				id = "main",
				sh = true,
				text = "ui_mcm_dogma_dont_reequip_pda_main_section",
				gr = dogma_mcm.with_header({
					{
						id = "main_description",
						type = "desc",
						text = "ui_mcm_dogma_dont_reequip_pda_main_description",
					},
					{
						id = "after_inventory",
						type = "check",
						val = 1,
						def = D["main/after_inventory"],
						hint = "dogma_dont_reequip_pda_after_inventory",
					},
					{
						id = "after_loot",
						type = "check",
						val = 1,
						def = D["main/after_loot"],
						hint = "dogma_dont_reequip_pda_after_loot",
					},
					{
						id = "after_teleport",
						type = "check",
						val = 1,
						def = D["main/after_teleport"],
						hint = "dogma_dont_reequip_pda_after_teleport",
					},
				}),
			},
			{
				id = "development",
				sh = true,
				text = "ui_mcm_dogma_dont_reequip_pda_development_section",
				gr = dogma_mcm.with_header({
					{
						id = "debug_log",
						type = "check",
						val = 1,
						def = D["development/debug_log"],
						hint = "dogma_dont_reequip_pda_debug_log",
					},
				}),
			},
		},
	}, "dogma"
end
