-- dogma_mcm_banner:begin (managed by sync-dogma-common.sh)
local function dogma_mcm()
	return _G.dogma_mcm
end
-- dogma_mcm_banner:end

function on_mcm_load()
	local MCM = dogma_mcm()
	return {
		id = "dont_reequip_pda",
		text = "ui_mcm_menu_dogma_dont_reequip_pda",
		gr = {
			{
				id = "main",
				sh = true,
				text = "ui_mcm_dogma_dont_reequip_pda_main_section",
				gr = MCM.with_header({
					{
						id = "main_description",
						type = "desc",
						text = "ui_mcm_dogma_dont_reequip_pda_main_description",
					},
					{
						id = "after_inventory",
						type = "check",
						val = 1,
						def = true,
						hint = "dogma_dont_reequip_pda_after_inventory",
					},
					{
						id = "after_loot",
						type = "check",
						val = 1,
						def = true,
						hint = "dogma_dont_reequip_pda_after_loot",
					},
					{
						id = "after_teleport",
						type = "check",
						val = 1,
						def = true,
						hint = "dogma_dont_reequip_pda_after_teleport",
					},
				}),
			},
			{
				id = "development",
				sh = true,
				text = "ui_mcm_dogma_dont_reequip_pda_development_section",
				gr = MCM.with_header({
					{
						id = "debug_log",
						type = "check",
						val = 1,
						def = false,
						hint = "dogma_dont_reequip_pda_debug_log",
					},
				}),
			},
		},
	}, "dogma"
end
