-- fixes/atmos_no_stealth_dependency conf

_G.dogma_fixes_atmos_no_stealth_dependency_conf = {
	MOD_ID = "dogma/fixes/atmos_no_stealth_dependency",
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "fixes", "ui_mcm_menu_dogma_fixes", {
		id = "atmos_no_stealth_dependency",
		sh = true,
		text = "ui_mcm_menu_dogma_fixes_atmos_no_stealth_dependency",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_fixes_atmos_no_stealth_dependency_page_description",
			},
		}),
	})
end
