-- gameplay/ads_zoom conf

_G.dogma_gameplay_ads_zoom_conf = {
	MOD_ID = "dogma/gameplay/ads_zoom",
	DEFAULTS = {
		["fov_zoom"] = 15,
		["wads_irons"] = 15,
		["wads_sight"] = 15,
		["wads_scope"] = 15,
		["dof"] = false,
		["dof_irons"] = 0.5,
		["dof_sight"] = 0.5,
		["dof_scope"] = 0.5,
		["wads_inc_key"] = -1,
		["wads_dec_key"] = -1,
		["wads_reset_key"] = -1,
		["wads_key_modifier"] = 0,
	},
}
