-- game/true_prone conf

_G.dogma_game_true_prone_conf = {
	MOD_ID = "dogma/game/true_prone",
	DEFAULTS = {
		enabled = true,
		hide_prone_bones = true,
		prone_damage_mult = 1.1,
	},
	loaded = {
		enabled = true,
		debug_log = true,
		debug_overlay = false,
		cam_height_stand = 1.65,
		cam_height_crouch = 1.2,
		cam_height_prone = 0.45,
	},
}

function on_mcm_load(options)
	local CONFIG = _G.dogma_game_true_prone_conf
	dogma_mcm.attach(options, "game", "ui_mcm_menu_dogma_game", {
		id = "true_prone",
		sh = true,
		text = "ui_mcm_menu_dogma_game_true_prone",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_game_true_prone_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS.enabled,
				hint = "dogma_game_true_prone_enabled",
			},
			{
				id = "hide_prone_bones",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS.hide_prone_bones,
				hint = "dogma_game_true_prone_hide_prone_bones",
			},
			{
				id = "prone_damage_mult",
				type = "track",
				val = 2,
				min = 1.1,
				max = 1.5,
				step = 0.05,
				def = CONFIG.DEFAULTS.prone_damage_mult,
				hint = "dogma_game_true_prone_prone_damage_mult",
			},
		}),
	})
end
