-- tweaks/grey_unpatched_outfit_patch conf (info-only MCM; always on while installed)

_G.dogma_tweaks_grey_unpatched_outfit_patch_conf = {
	MOD_ID = "dogma/tweaks/grey_unpatched_outfit_patch",
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "grey_unpatched_outfit_patch_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_grey_unpatched_outfit_patch_page_description",
		},
	})
end
