-- travel/true_fast_travel conf

_G.dogma_travel_true_fast_travel_conf = {
	MOD_ID = "dogma/travel/true_fast_travel",
	DEFAULTS = {
		["block_transition_in_combat"] = true,
		["message_duration"] = 20,
		["show_ambush_range"] = true,
		["fade_travel"] = false,
		["path_preview"] = true,
		["visited_radius_m"] = 30,
		["fly_camera"] = true,
		["fly_speed_mult_normal"] = 5,
		["fly_speed_mult_sneak"] = 2,
		["companion_teleport_key"] = -1,
	},
}
