function on_mcm_load(options)
	local CONFIG = _G.dogma_game_safety_save_conf
	dogma_mcm.attach(options, "game", "ui_mcm_menu_dogma_game", {
		id = "safety_save",
		sh = true,
		text = "ui_mcm_menu_dogma_game_safety_save",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_game_safety_save_page_description",
			},
			{
				id = "always_min",
				type = "track",
				val = 2,
				min = 0,
				max = 30,
				step = 1,
				def = CONFIG.DEFAULTS["always_min"],
				hint = "dogma_game_safety_save_always_min",
			},
			{
				id = "event_min",
				type = "track",
				val = 2,
				min = 1,
				max = 15,
				step = 1,
				def = CONFIG.DEFAULTS["event_min"],
				hint = "dogma_game_safety_save_event_min",
			},
		}),
	})
end
