function on_mcm_load(options)
	local CONFIG = _G.dogma_hud_bhs_on_damage_conf
	dogma.mcm.attach(options, "hud", "ui_mcm_menu_dogma_hud", {
		id = "bhs_on_damage",
		sh = true,
		text = "ui_mcm_menu_dogma_hud_bhs_on_damage",
		gr = dogma.mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_hud_bhs_on_damage_page_description",
			},
			{
				id = "sec",
				type = "track",
				val = 2,
				min = 0,
				max = 20,
				step = 1,
				def = CONFIG.DEFAULTS["sec"],
				hint = "dogma_hud_bhs_on_damage_sec",
			},
		}),
	})
end
