function on_mcm_load(options)
	local CONFIG = _G.dogma_gameplay_parts_in_stashes_conf

	dogma_mcm.attach(options, "gameplay", "ui_mcm_menu_dogma_gameplay", {
		id = "parts_in_stashes",
		sh = true,
		text = "ui_mcm_menu_dogma_gameplay_parts_in_stashes",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_gameplay_parts_in_stashes_page_description",
			},
			{
				id = "parts_chance",
				type = "track",
				val = 2,
				min = 0,
				max = 50,
				step = 1,
				def = CONFIG.DEFAULTS["parts_chance"],
				hint = "dogma_gameplay_parts_in_stashes_parts_chance",
			},
			{
				id = "max_parts",
				type = "track",
				val = 2,
				min = 1,
				max = 3,
				step = 1,
				def = CONFIG.DEFAULTS["max_parts"],
				hint = "dogma_gameplay_parts_in_stashes_max_parts",
			},
		}),
	})
end
