-- game/belt_glowsticks conf

_G.dogma_game_belt_glowsticks_conf = {
	MOD_ID = "dogma/game/belt_glowsticks",
	DEFAULTS = {
		["dblclick_to_belt"] = true,
	},
	loaded = {
		dblclick_to_belt = true,
	},
}

function on_mcm_load(options)
	local CONFIG = _G.dogma_game_belt_glowsticks_conf
	dogma_mcm.attach(options, "game", "ui_mcm_menu_dogma_game", {
		id = "belt_glowsticks",
		sh = true,
		text = "ui_mcm_menu_dogma_game_belt_glowsticks",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_game_belt_glowsticks_page_description",
			},
			{
				id = "dblclick_to_belt",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["dblclick_to_belt"],
				hint = "dogma_game_belt_glowsticks_dblclick_to_belt",
			},
		}),
	})
end
