function on_mcm_load(options)
	local CONF = _G.dogma_pda_rep_warning_conf
	local D = CONF.defaults
	dogma_mcm.attach(options, "pda", "ui_mcm_menu_dogma_pda", {
		id = "rep_warning",
		sh = true,
		text = "ui_mcm_menu_dogma_pda_rep_warning",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_pda_rep_warning_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = D["enabled"],
				hint = "dogma_pda_rep_warning_enabled",
			},
		}),
	})
end
