function on_mcm_load(options)
	local CONF = _G.dogma_disassembly_tools_conf
	local D = CONF.defaults
	dogma_mcm.attach(options, "disassembly", "ui_mcm_menu_dogma_disassembly", {
		id = "tools",
		sh = true,
		text = "ui_mcm_menu_dogma_disassembly_tools",
		gr = dogma_mcm.with_header({
			{
				id = "main_description",
				type = "desc",
				text = "ui_mcm_dogma_optimal_tool_use_main_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = D["enabled"],
				hint = "dogma_optimal_tool_use_enabled",
			},
		}),
	})
end
