function on_mcm_load()
	local CONF = _G.dogma_optimal_tool_use_conf
	local D = CONF.defaults
	return {
		id = "optimal_tool_use",
		text = "ui_mcm_menu_dogma_optimal_tool_use",
		gr = {
			{
				id = "main",
				sh = true,
				text = "ui_mcm_dogma_optimal_tool_use_main_section",
				gr = dogma_mcm.with_header({
					{
						id = "main_description",
						type = "desc",
						text = "ui_mcm_dogma_optimal_tool_use_main_description",
					},
					{
						id = "enabled",
						type = "check",
						val = 1,
						def = D["main/enabled"],
						hint = "dogma_optimal_tool_use_enabled",
					},
				}),
			},
			{
				id = "development",
				sh = true,
				text = "ui_mcm_dogma_optimal_tool_use_development_section",
				gr = dogma_mcm.with_header({
					{
						id = "debug_log",
						type = "check",
						val = 1,
						def = D["development/debug_log"],
						hint = "dogma_optimal_tool_use_debug_log",
					},
				}),
			},
		},
	}, "dogma"
end
