-- dogma_mcm_banner:begin (managed by sync-dogma-common.sh)
local function dogma_mcm()
	return _G.dogma_mcm
end
-- dogma_mcm_banner:end

function on_mcm_load()
	local MCM = dogma_mcm()
	return {
		id = "optimal_tool_use",
		text = "ui_mcm_menu_dogma_optimal_tool_use",
		gr = {
			{
				id = "main",
				sh = true,
				text = "ui_mcm_dogma_optimal_tool_use_main_section",
				gr = MCM.with_header({
					{
						id = "main_description",
						type = "desc",
						text = "ui_mcm_dogma_optimal_tool_use_main_description",
					},
					{
						id = "enabled",
						type = "check",
						val = 1,
						def = true,
						hint = "dogma_optimal_tool_use_enabled",
					},
				}),
			},
			{
				id = "development",
				sh = true,
				text = "ui_mcm_dogma_optimal_tool_use_development_section",
				gr = MCM.with_header({
					{
						id = "debug_log",
						type = "check",
						val = 1,
						def = false,
						hint = "dogma_optimal_tool_use_debug_log",
					},
				}),
			},
		},
	}, "dogma"
end
