#!/usr/bin/env bash
# Build a FOMOD-ready release tree under build/fomod/.
#
# Layout:
#   build/fomod/
#     fomod/ModuleConfig.xml  info.xml  images/<id>.png
#     common/gamedata/...
#     <feature_id>/gamedata/...
#     meta.ini  .mod_id
#
# Local full deploy is still tools/build.sh (all features merged).
# This script is for the GitHub release zip / MO2 installer wizard.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/src"
STAGE="$ROOT/build/fomod"
BUILD="$ROOT/tools/build.sh"

xml_escape() {
	sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/"/\&quot;/g'
}

read_trim() {
	local f="$1"
	[[ -f "$f" ]] || { echo ""; return 0; }
	tr -d '\r' < "$f" | sed -e 's/[[:space:]]*$//' | awk 'NR==1{printf "%s",$0; next}{printf "\n%s",$0}'
}

if [[ ! -f "$BUILD" ]]; then
	echo "package-fomod: missing $BUILD" >&2
	exit 1
fi

rm -rf "$STAGE"
mkdir -p "$STAGE/fomod/images"

VERSION="$(grep -E '^version=' "$ROOT/meta.ini" | head -1 | cut -d= -f2 | tr -d '[:space:]')"
[[ -n "$VERSION" ]] || VERSION="0.0.0"

echo "package-fomod: common"
DOGMA_OUT="$STAGE/common/gamedata" DOGMA_ONLY=common bash "$BUILD"

plugins_xml=""
feature_count=0

while IFS= read -r -d '' cat_dir; do
	[[ -d "$cat_dir" ]] || continue
	cat_base="$(basename "$cat_dir")"
	[[ "$cat_base" == "common" ]] && continue
	case "$cat_base" in
		scripts | configs | textures | meshes | anims | sounds | spawns) continue ;;
	esac

	while IFS= read -r -d '' feat_dir; do
		[[ -d "$feat_dir" ]] || continue
		feat_base="$(basename "$feat_dir")"
		case "$feat_base" in
			assets | installer) continue ;;
		esac
		rel="${feat_dir#"$SRC"/}"
		rel="${rel//\\/\/}"

		inst="$feat_dir/installer"
		id="$feat_base"
		if [[ -f "$inst/id.txt" ]]; then
			id="$(read_trim "$inst/id.txt")"
		fi
		name="$feat_base"
		if [[ -f "$inst/name.txt" ]]; then
			name="$(read_trim "$inst/name.txt")"
		fi
		desc="DOGMA feature: $name"
		if [[ -f "$inst/description.txt" ]]; then
			desc="$(read_trim "$inst/description.txt")"
		fi
		default="Optional"
		if [[ -f "$inst/default.txt" ]]; then
			case "$(read_trim "$inst/default.txt" | tr '[:upper:]' '[:lower:]')" in
				recommended) default="Recommended" ;;
				required) default="Required" ;;
				*) default="Optional" ;;
			esac
		fi

		echo "package-fomod: $rel -> $id"
		DOGMA_OUT="$STAGE/$id/gamedata" DOGMA_ONLY="$rel" bash "$BUILD"

		image_xml=""
		if [[ -f "$inst/image.png" ]]; then
			cp -a "$inst/image.png" "$STAGE/fomod/images/${id}.png"
			image_xml=$'\n\t\t\t\t\t\t\t'"<image path=\"fomod\\images\\${id}.png\" />"
		fi

		name_x="$(printf '%s' "$name" | xml_escape)"
		desc_x="$(printf '%s' "$desc" | xml_escape)"

		plugins_xml+="$(cat <<EOF

						<plugin name="${name_x}">
							<description>${desc_x}</description>${image_xml}
							<files>
								<folder source="${id}\\gamedata" destination="gamedata" priority="0" />
							</files>
							<typeDescriptor>
								<type name="${default}"/>
							</typeDescriptor>
						</plugin>
EOF
)"
		feature_count=$((feature_count + 1))
	done < <(find "$cat_dir" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)
done < <(find "$SRC" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

if [[ "$feature_count" -eq 0 ]]; then
	echo "package-fomod: no features found" >&2
	exit 1
fi

cat > "$STAGE/fomod/info.xml" <<EOF
<fomod>
	<Name>DOGMA</Name>
	<Author>Dorn</Author>
	<Version>${VERSION}</Version>
	<Website>https://github.com/JoshuaCarter/DOGMA</Website>
	<Description>Dorn's Own GAMMA Mods and Alterations — pick the features you want. Core (DORN common) is always installed.</Description>
	<Groups>
		<element>Miscellaneous</element>
	</Groups>
</fomod>
EOF

cat > "$STAGE/fomod/ModuleConfig.xml" <<EOF
<!-- Generated by tools/package-fomod.sh — do not hand-edit; change src/*/installer/ instead. -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://qconsulting.ca/fo3/ModConfig5.0.xsd">
	<moduleName>DOGMA</moduleName>
	<requiredInstallFiles>
		<folder source="common\\gamedata" destination="gamedata" />
	</requiredInstallFiles>
	<installSteps order="Explicit">
		<installStep name="Features">
			<optionalFileGroups order="Explicit">
				<group name="Select features to install" type="SelectAny">
					<plugins order="Explicit">${plugins_xml}
					</plugins>
				</group>
			</optionalFileGroups>
		</installStep>
	</installSteps>
</config>
EOF

cp -a "$ROOT/meta.ini" "$STAGE/meta.ini"
if [[ -f "$ROOT/.mod_id" ]]; then
	cp -a "$ROOT/.mod_id" "$STAGE/.mod_id"
fi

echo "package-fomod: done ($feature_count features) -> ${STAGE#"$ROOT"/}"
