#!/usr/bin/env python3
"""Pull non-default MCM options from axr_options.ltx into config/initialize.ini.

Compares the live [mcm] section against def= values found in mods' *mcm*.script
files. Options that match their script default are skipped. Remaining keys are
grouped into [MO2 mod name] sections when the MCM root id can be mapped to a
mod folder; otherwise the MCM path prefix is used as the section name.

  py -3 tools/pull_mcm_initialize.py
  python3 tools/pull_mcm_initialize.py --dry-run
  python3 tools/pull_mcm_initialize.py --include-dogma
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from collections import defaultdict
from pathlib import Path


HEADER = """; DOGMA - initialize base GAMMA / third-party MCM settings
;
; Auto-generated by tools/pull_mcm_initialize.py from your axr_options.ltx
; (non-default MCM values only). Edit freely.
;
; Each [section] is an MO2 mod name (substring match, same style as disable.ini).
; If that mod is present in the profile modlist (+ or -), the key=value lines
; under it are written into axr_options.ltx.
;
; Keys default to the [mcm] section. Prefix with @OtherSection/ to target
; another axr_options section, e.g. @lower_weapon_sprint/blacklist = ...
;
; Comment out a line or whole section to skip it.
; Close MO2 before running so it does not overwrite files on exit.

"""


def info(msg: str) -> None:
    print(msg)


def warn(msg: str) -> None:
    print(msg, file=sys.stderr)


def repo_root_from_script() -> Path:
    return Path(__file__).resolve().parent.parent


def read_mo2_ini_value(ini_path: Path, key: str) -> str:
    prefix = re.compile(rf"^\s*{re.escape(key)}\s*=")
    for raw in ini_path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not prefix.match(raw):
            continue
        m = re.search(r"@ByteArray\((.+)\)\s*$", raw)
        if m:
            value = m.group(1)
        else:
            value = raw.split("=", 1)[1].strip()
        return value.replace("\\\\", "\\")
    raise ValueError(f"{key} not found in {ini_path}")


def find_axr_options(mo2_root: Path) -> Path:
    mods = mo2_root / "mods"
    if not mods.is_dir():
        raise FileNotFoundError(f"mods folder not found: {mods}")
    candidates = sorted(mods.rglob("axr_options.ltx"))
    if not candidates:
        overwrite = mo2_root / "overwrite" / "gamedata" / "configs" / "axr_options.ltx"
        if overwrite.is_file():
            return overwrite
        raise FileNotFoundError(f"No axr_options.ltx under {mods}")
    for path in candidates:
        lower = str(path).lower()
        if "mcm values" in lower or "mcm_values" in lower:
            return path
    return candidates[0]


def parse_axr_section(path: Path, section: str) -> dict[str, str]:
    want = f"[{section}]".lower()
    out: dict[str, str] = {}
    in_section = False
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        s = line.strip()
        if s.startswith("[") and s.endswith("]"):
            in_section = s.lower() == want
            continue
        if not in_section or not s or s.startswith(";"):
            continue
        if "=" not in s:
            continue
        key, val = s.split("=", 1)
        out[key.strip()] = val.strip()
    return out


_ID_DEF_LINE = re.compile(
    r"""(?ix)
    id\s*=\s*['"]([^'"]+)['"]
    .*?
    def\s*=\s*
    (
        -?\d+(?:\.\d+)?
        | true | false
        | ['"][^'"]*['"]
    )
    """
)
_ROOT_ID = re.compile(
    r"""(?ix)
    (?:function\s+on_mcm_load|return\s*\{)
    .*?
    id\s*=\s*['"]([^'"]+)['"]
    """,
    re.DOTALL,
)
_SIMPLE_ROOT = re.compile(
    r"""(?ix)
    ^\s*(?:op\s*=\s*)?\{\s*
    id\s*=\s*['"]([^'"]+)['"]
    """,
    re.MULTILINE,
)


def normalize_def(raw: str) -> str:
    raw = raw.strip()
    if (raw.startswith("'") and raw.endswith("'")) or (
        raw.startswith('"') and raw.endswith('"')
    ):
        return raw[1:-1]
    if raw.lower() in ("true", "false"):
        return raw.lower()
    return raw


def normalize_val(raw: str) -> str:
    raw = raw.strip()
    if raw.lower() in ("true", "false"):
        return raw.lower()
    return raw


def collect_mcm_defaults(mo2_root: Path) -> tuple[dict[str, str], dict[str, str]]:
    """Return (path_or_leaf -> def, root_id -> mod_folder_name)."""
    defaults: dict[str, str] = {}
    root_to_mod: dict[str, str] = {}
    mods = mo2_root / "mods"
    if not mods.is_dir():
        return defaults, root_to_mod

    for script in mods.rglob("*.script"):
        name = script.name.lower()
        if "mcm" not in name and not name.endswith("_mcm.script"):
            continue
        try:
            text = script.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        mod_folder = script.relative_to(mods).parts[0]

        root = None
        m = _ROOT_ID.search(text)
        if m:
            root = m.group(1)
        else:
            m2 = _SIMPLE_ROOT.search(text)
            if m2:
                root = m2.group(1)
        if root:
            root_to_mod.setdefault(root, mod_folder)

        for m in _ID_DEF_LINE.finditer(text):
            opt_id, def_raw = m.group(1), normalize_def(m.group(2))
            defaults[opt_id] = def_raw
            if root and opt_id != root:
                defaults[f"{root}/{opt_id}"] = def_raw

    return defaults, root_to_mod


_KEYBIND_LEAF = re.compile(
    r"(?i)^(?:key(?:_.+)?|.+_key|keybind(?:_.+)?|.+_keybind|key_bind(?:_.+)?|"
    r".+_key_bind|hotkey(?:_.+)?|.+_hotkey|bind(?:_.+)?|.+_bind|second_key)$"
)


def is_unbound_keybind(key: str, val: str) -> bool:
    leaf = key.split("/")[-1]
    return val.strip() == "-1" and bool(_KEYBIND_LEAF.match(leaf))


def lookup_default(key: str, defaults: dict[str, str]) -> str | None:
    if key in defaults:
        return defaults[key]
    parts = key.split("/")
    if len(parts) >= 2:
        # Flat MCM trees often store def under root/leaf even when axr has deeper paths.
        guess = f"{parts[0]}/{parts[-1]}"
        if guess in defaults:
            return defaults[guess]
    return None


def section_for_key(key: str, root_to_mod: dict[str, str]) -> str:
    prefix = key.split("/", 1)[0]
    return root_to_mod.get(prefix, prefix)


def format_initialize(groups: dict[str, list[tuple[str, str]]]) -> str:
    lines = [HEADER.rstrip(), ""]
    for section in sorted(groups.keys(), key=str.lower):
        lines.append(f"[{section}]")
        for key, val in sorted(groups[section], key=lambda kv: kv[0].lower()):
            lines.append(f"{key} = {val}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Pull non-default MCM options into config/initialize.ini"
    )
    p.add_argument(
        "--mo2-root",
        default=r"C:\GAMMA" if sys.platform == "win32" else os.environ.get("MO2_ROOT", r"C:\GAMMA"),
        help="MO2 / GAMMA install folder. Default: C:\\GAMMA",
    )
    p.add_argument(
        "--axr-options",
        default="",
        help="Path to axr_options.ltx (default: auto-detect MCM values mod)",
    )
    p.add_argument(
        "--output",
        default="",
        help="Output initialize.ini (default: <repo>/config/initialize.ini)",
    )
    p.add_argument(
        "--include-dogma",
        action="store_true",
        help="Include dogma/* MCM keys (excluded by default)",
    )
    p.add_argument(
        "--keep-unbound-keys",
        action="store_true",
        help="Keep keybind options that are already -1 (skipped by default)",
    )
    p.add_argument(
        "--all-saved",
        action="store_true",
        help="Ignore script defaults; pull every saved [mcm] key (still applies dogma/key filters)",
    )
    p.add_argument("--dry-run", action="store_true", help="Print summary; do not write")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = repo_root_from_script()
    mo2_root = Path(args.mo2_root)
    out_path = Path(args.output) if args.output else root / "config" / "initialize.ini"

    if not (mo2_root / "ModOrganizer.exe").is_file():
        warn(f"ModOrganizer.exe not found under: {mo2_root}")
        warn("Pass --mo2-root path/to/GAMMA")
        return 1

    axr = Path(args.axr_options) if args.axr_options else find_axr_options(mo2_root)
    if not axr.is_file():
        warn(f"axr_options.ltx not found: {axr}")
        return 1

    info(f"MO2 root : {mo2_root}")
    info(f"axr_options: {axr}")
    info(f"Output   : {out_path}")

    saved = parse_axr_section(axr, "mcm")
    info(f"Saved [mcm] keys: {len(saved)}")

    defaults, root_to_mod = collect_mcm_defaults(mo2_root)
    info(f"Script defaults indexed: {len(defaults)} (roots mapped: {len(root_to_mod)})")

    kept = 0
    skipped_default = 0
    skipped_dogma = 0
    skipped_unbound = 0
    groups: dict[str, list[tuple[str, str]]] = defaultdict(list)

    for key, val in saved.items():
        if not args.include_dogma and key.lower().startswith("dogma/"):
            skipped_dogma += 1
            continue
        if not args.keep_unbound_keys and is_unbound_keybind(key, val):
            skipped_unbound += 1
            continue
        if not args.all_saved:
            d = lookup_default(key, defaults)
            if d is not None and normalize_val(val) == normalize_val(d):
                skipped_default += 1
                continue
        section = section_for_key(key, root_to_mod)
        groups[section].append((key, val))
        kept += 1

    info(
        f"Kept {kept} | skipped default={skipped_default} "
        f"dogma={skipped_dogma} unbound_keys={skipped_unbound} | sections={len(groups)}"
    )

    text = format_initialize(groups)
    if args.dry_run:
        info("Dry run - not writing. First sections:")
        preview = "\n".join(text.splitlines()[:40])
        info(preview)
        if text.count("\n") > 40:
            info("...")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    if out_path.is_file():
        bak = out_path.with_suffix(out_path.suffix + ".bak")
        bak.write_bytes(out_path.read_bytes())
        info(f"Backup   : {bak}")
    out_path.write_text(text, encoding="utf-8", newline="\n")
    info(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (FileNotFoundError, ValueError, OSError) as exc:
        warn(str(exc))
        raise SystemExit(1) from exc
