function on_mcm_load(options)
	local CONF = _G.dogma_misc_missions_conf
	local D = CONF.defaults
	dogma_mcm.attach(options, "misc", "ui_mcm_menu_dogma_misc", {
		id = "missions",
		sh = true,
		text = "ui_mcm_menu_dogma_misc_missions",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_misc_missions_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = D["enabled"],
				hint = "dogma_misc_missions_enabled",
			},
		}),
	})
end
