-- tweaks/no_guide_job_money_penalty conf (info-only MCM; always on while installed)

_G.dogma_tweaks_no_guide_job_money_penalty_conf = {
	MOD_ID = "dogma/tweaks/no_guide_job_money_penalty",
}

function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "no_guide_job_money_penalty_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_no_guide_job_money_penalty_page_description",
		},
	})
end
