function on_mcm_load(options)
	local CONFIG = _G.dogma_game_death_report_conf
	dogma_mcm.attach(options, "game", "ui_mcm_menu_dogma_game", {
		id = "death_report",
		sh = true,
		text = "ui_mcm_menu_dogma_game_death_report",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_game_death_report_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["enabled"],
				hint = "dogma_game_death_report_enabled",
			},
		}),
	})
end
