function on_mcm_load(options)
	local CONFIG = _G.dogma_game_campfire_healing_conf
	dogma_mcm.attach(options, "game", "ui_mcm_menu_dogma_game", {
		id = "campfire_healing",
		sh = true,
		text = "ui_mcm_menu_dogma_game_campfire_healing",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_game_campfire_healing_page_description",
			},
			{
				id = "range_m",
				type = "track",
				val = 2,
				min = 0,
				max = 5,
				step = 0.1,
				def = CONFIG.DEFAULTS["range_m"],
				hint = "dogma_game_campfire_healing_range_m",
			},
			{
				id = "pause_in_combat",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["pause_in_combat"],
				hint = "dogma_game_campfire_healing_pause_in_combat",
			},
			{
				id = "body_sec",
				type = "track",
				val = 2,
				min = 30,
				max = 100,
				step = 1,
				def = CONFIG.DEFAULTS["body_sec"],
				hint = "dogma_game_campfire_healing_body_sec",
			},
			{
				id = "limb_sec",
				type = "track",
				val = 2,
				min = 20,
				max = 100,
				step = 1,
				def = CONFIG.DEFAULTS["limb_sec"],
				hint = "dogma_game_campfire_healing_limb_sec",
			},
			{
				id = "fx_enable",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["fx_enable"],
				hint = "dogma_game_campfire_healing_fx_enable",
			},
			{
				id = "fx_intensity",
				type = "track",
				val = 2,
				min = 0,
				max = 1,
				step = 0.05,
				def = CONFIG.DEFAULTS["fx_intensity"],
				hint = "dogma_game_campfire_healing_fx_intensity",
			},
		}),
	})
end
