-- gui/fx_radiation conf

_G.dogma_gui_fx_radiation_conf = {
	MOD_ID = "dogma/gui/fx_radiation",
	DEFAULTS = {
		["desaturation/blur_max"] = 2000,
		["desaturation/blur_min"] = 500,
		["desaturation/enable"] = true,
		["duality/dual_max"] = 2000,
		["duality/dual_min"] = 1000,
		["duality/enable"] = true,
		["grain/enable"] = true,
		["grain/level_01_msv"] = 50,
		["grain/level_02_msv"] = 100,
		["grain/level_03_msv"] = 150,
		["grain/level_04_msv"] = 250,
		["grain/level_05_msv"] = 350,
		["grain/level_06_msv"] = 450,
		["grain/level_07_msv"] = 550,
		["grain/level_08_msv"] = 700,
		["grain/level_09_msv"] = 850,
		["grain/level_10_msv"] = 1000,
	},
	-- Filled by on_option_change (runs at boot before any read).
	loaded = {},
}
