-- tweaks/fix_geiger_for_dynamic_rad_patches conf (info-only MCM; LTX registers dynamic rad zones for dosimeter)



_G.dogma_tweaks_fix_geiger_for_dynamic_rad_patches_conf = {

	MOD_ID = "dogma/tweaks/fix_geiger_for_dynamic_rad_patches",

	DEFAULTS = {},

}


function on_mcm_load(options)
	dogma_mcm.append(options, "tweaks", "ui_mcm_menu_dogma_tweaks", {
		{
			id = "fix_geiger_for_dynamic_rad_patches_description",
			type = "desc",
			text = "ui_mcm_dogma_tweaks_fix_geiger_for_dynamic_rad_patches_page_description",
		},
	})
end
