function on_mcm_load(options)
	local CONFIG = _G.dogma_player_scanner_keys_conf
	dogma_mcm.attach(options, "player", "ui_mcm_menu_dogma_player", {
		id = "scanner_keys",
		sh = true,
		text = "ui_mcm_menu_dogma_player_scanner_keys",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_scanner_keys_page_description",
			},
			{
				id = "enabled",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS["enabled"],
				hint = "dogma_scanner_keys_enabled",
			},
			{ id = "line_keys", type = "line" },
			{
				id = "key_detector",
				type = "key_bind",
				val = 2,
				def = CONFIG.DEFAULTS["key_detector"],
				hint = "dogma_scanner_keys_key_detector",
			},
			{
				id = "key_dosimeter",
				type = "key_bind",
				val = 2,
				def = CONFIG.DEFAULTS["key_dosimeter"],
				hint = "dogma_scanner_keys_key_dosimeter",
			},
			{
				id = "key_radio",
				type = "key_bind",
				val = 2,
				def = CONFIG.DEFAULTS["key_radio"],
				hint = "dogma_scanner_keys_key_radio",
			},
		}),
	})
end
