-- perf/sfx_prefetcher conf

_G.dogma_perf_sfx_prefetcher_conf = {
	MOD_ID = "dogma/perf/sfx_prefetcher",
	DEFAULTS = {
		enable = true,
	},
	loaded = {},
}

local CONFIG = _G.dogma_perf_sfx_prefetcher_conf

function on_mcm_load(options)
	dogma_mcm.attach(options, "perf", "ui_mcm_menu_dogma_perf", {
		id = "sfx_prefetcher",
		sh = true,
		text = "ui_mcm_menu_dogma_perf_sfx_prefetcher",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_perf_sfx_prefetcher_page_description",
			},
			{
				id = "enable",
				type = "check",
				val = 1,
				def = CONFIG.DEFAULTS.enable,
				hint = "dogma_perf_sfx_prefetcher_enable",
			},
		}),
	})
end
