-- game/escort_tweaks conf

_G.dogma_game_escort_tweaks_conf = {
	MOD_ID = "dogma/game/escort_tweaks",
}

function on_mcm_load(options)
	dogma_mcm.attach(options, "game", "ui_mcm_menu_dogma_game", {
		id = "escort_tweaks",
		sh = true,
		text = "ui_mcm_menu_dogma_game_escort_tweaks",
		gr = dogma_mcm.with_header({
			{
				id = "page_description",
				type = "desc",
				text = "ui_mcm_dogma_game_escort_tweaks_page_description",
			},
		}),
	})
end
